/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package coffeemachine;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Scanner in = new Scanner(System.in);
        CoffeeMachine cm = new CoffeeMachine(400, 540, 120, 9, 550);
        cm.powerOnCoffeeMachine(in);
        in.close();
    }
}
