server:
  port: 8080
  error:
    path: /error2
spring:
  thymeleaf:
    cache: false
    enabled: true 
    prefix: classpath:/templates/
    suffix: .html
  application:
    name: Book Reservation System
